## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'], axis=1)

In [ ]:
# Determine the number of unique values in each column.
unique_value_counts = application_df.nunique()

print(unique_value_counts)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
print(application_type_counts)

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
cutoff_value = 700

# use the variable name `application_types_to_replace`
application_types_to_replace = application_type_counts[application_type_counts < cutoff_value].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
Other      804
T8         737
T7         725
Name: APPLICATION_TYPE, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts_above_1 = classification_counts[classification_counts > 1]
print(classification_counts_above_1)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
cutoff_value = 700

# use the variable name `classifications_to_replace`
classifications_to_replace = classification_counts[classification_counts < cutoff_value].index.tolist()

# Replace in the DataFrame
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls, "Other")

# Check the value counts after binning
print(application_df['CLASSIFICATION'].value_counts())

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: CLASSIFICATION, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df,dtype=float)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values

In [ ]:
X = application_df.drop('IS_SUCCESSFUL', axis=1).values

In [ ]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len( X_train_scaled[0])
hidden_nodes_layer1=80
hidden_nodes_layer2=30

model = tf.keras.models.Sequential()

# First hidden layer
model.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
model.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 80)                3520

 dense_4 (Dense)             (None, 30)                2430

 dense_5 (Dense)             (None, 1)                 31

=================================================================
Total params: 5,981
Trainable params: 5,981
Non-trainable params: 0
_________________________________________________________________

In [ ]:
# Compile the model
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Train the model
fit_model = model.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5698 - accuracy: 0.7213
Epoch 2/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5533 - accuracy: 0.7290
Epoch 3/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5500 - accuracy: 0.7315
Epoch 4/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5488 - accuracy: 0.7307
Epoch 5/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5473 - accuracy: 0.7313
Epoch 6/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7323
Epoch 7/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5456 - accuracy: 0.7330
Epoch 8/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5451 - accuracy: 0.7329
Epoch 9/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5446 - accuracy: 0.7343
Epoch 10/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5440 - accuracy: 0.7327
Epoch 11/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5435 - accuracy: 0.7337
Epoch 12/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5435 - accuracy: 0.7341
Epoch 13/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7343
Epoch 14/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7341
Epoch 15/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7351
Epoch 16/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7360
Epoch 17/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7352
Epoch 18/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7363
Epoch 19/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7363
Epoch 20/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7364
Epoch 21/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7356
Epoch 22/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7369
Epoch 23/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7367
Epoch 24/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7371
Epoch 25/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7364
Epoch 26/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5395 - accuracy: 0.7372
Epoch 27/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7357
Epoch 28/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7366
Epoch 29/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7375
Epoch 30/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7380
Epoch 31/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7368
Epoch 32/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7368
Epoch 33/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5381 - accuracy: 0.7373
Epoch 34/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7376
Epoch 35/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7380
Epoch 36/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7383
Epoch 37/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7372
Epoch 38/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7381
Epoch 39/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7381
Epoch 40/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7387
Epoch 41/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7383
Epoch 42/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7387
Epoch 43/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7383
Epoch 44/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5373 - accuracy: 0.7382
Epoch 45/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7388
Epoch 46/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7382
Epoch 47/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5364 - accuracy: 0.7384
Epoch 48/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7387
Epoch 49/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7387
Epoch 50/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7397
Epoch 51/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7383
Epoch 52/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7389
Epoch 53/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7383
Epoch 54/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7396
Epoch 55/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5359 - accuracy: 0.7391
Epoch 56/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7385
Epoch 57/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7393
Epoch 58/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7392
Epoch 59/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7395
Epoch 60/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7393
Epoch 61/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7398
Epoch 62/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5358 - accuracy: 0.7402
Epoch 63/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7393
Epoch 64/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7394
Epoch 65/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7395
Epoch 66/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7394
Epoch 67/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7391
Epoch 68/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7397
Epoch 69/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5355 - accuracy: 0.7395
Epoch 70/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7399
Epoch 71/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7389
Epoch 72/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7402
Epoch 73/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5352 - accuracy: 0.7396
Epoch 74/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7392
Epoch 75/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7394
Epoch 76/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5347 - accuracy: 0.7395
Epoch 77/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5351 - accuracy: 0.7397
Epoch 78/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7396
Epoch 79/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7402
Epoch 80/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7402
Epoch 81/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7399
Epoch 82/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7406
Epoch 83/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7403
Epoch 84/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5345 - accuracy: 0.7394
Epoch 85/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7392
Epoch 86/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7402
Epoch 87/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7399
Epoch 88/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7398
Epoch 89/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7402
Epoch 90/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7396
Epoch 91/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5343 - accuracy: 0.7402
Epoch 92/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7401
Epoch 93/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7400
Epoch 94/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7402
Epoch 95/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7402
Epoch 96/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7404
Epoch 97/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7393
Epoch 98/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7396
Epoch 99/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5339 - accuracy: 0.7403
Epoch 100/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7401

In [ ]:
# Export our model to HDF5 file
from google.colab import files

model.save('AlphabetSoupCharity.h5')
files.download('AlphabetSoupCharity.h5')